apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pod-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-service
  template:
    metadata:
      labels:
        app: test-service
    spec:
      containers:
        - name: service
          image: nginx
